<?php

namespace PWD\AnimeBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * AnimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimeRepository extends \Doctrine\ORM\EntityRepository{
    public function getAnimeSearch($keywords,$genre,$nbPerPage,$page){
        $sql= $this->createQueryBuilder('a')
                ->where("a.title LIKE :keywords")
                ->andWhere("a.genre LIKE :genre")
                ->setParameter("keywords", "%".$keywords."%")
                ->setParameter("genre", "%".$genre."%");
        $sql->setFirstResult(($page - 1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($sql, true);
    }
}
