<?php

namespace PWD\AnimeBundle\Repository;

/**
 * ImgMinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgMinRepository extends \Doctrine\ORM\EntityRepository
{
}
