services:
    pwd_anime.menu:
        class: PWD\AnimeBundle\Menu\PWDMenu
        arguments: ["@form.factory","@router"]
#    pwd_anime.example:
#        class: PWD\AnimeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
